apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hello-world-s2i
  namespace: openshift-gitops
spec:
  destination:
    server: 'https://kubernetes.default.svc'
  project: default
  source:
    directory:
      recurse: true
    path: manifests/s2i
    repoURL: 'https://github.com/shirodkar/helloworld-ear.git'
    targetRevision: HEAD
  syncPolicy:
    automated:
      enabled: true
      prune: true
      selfHeal: true