apiVersion: console.openshift.io/v1
kind: ConsolePlugin
metadata:
  name: gitops-plugin
spec:
  backend:
    service:
      basePath: /
      name: gitops-plugin
      namespace: openshift-gitops
      port: 9001
    type: Service
  displayName: GitOps Plugin
  i18n:
    loadType: Preload
---
apiVersion: operator.openshift.io/v1
kind: Console
metadata:
  name: cluster
  annotations:
    argocd.argoproj.io/sync-options: ServerSideApply=true
spec:
  plugins:
    - gitops-plugin