apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: rhel9-demo
spec:
  running: true
  template:
    metadata:
      labels:
        app: lightspeed-demo
    spec:
      architecture: amd64
      domain:
        cpu:
          cores: 1
          sockets: 1
          threads: 1
        devices:
          disks:
            - disk:
                bus: virtio
              name: rootdisk
            - disk:
                bus: virtio
              name: cloudinitdisk
        firmware:
          serial: 6a9989d5-87ed-41bd-baa4-ba9cc49155b2
          uuid: c5d4310e-528f-4608-896d-133db565cd75
        machine:
          type: pc-q35-rhel9.4.0
        resources:
          requests:
            memory: 2Gi
      networks:
        - name: default
          pod: {}
      volumes:
        - containerDisk:
            image: 'quay.io/containerdisks/rhel:9-latest'
          name: rootdisk
        - cloudInitNoCloud:
            userData: |
              #cloud-config
              user: cloud-user
              password: redhat
              chpasswd:
                expire: false
              ssh_pwauth: true
          name: cloudinitdisk