apiVersion: wildfly.org/v1alpha1
kind: WildFlyServer
metadata:
  name: app-inventory
spec:
  applicationImage: 'quay.io/rh_ee_sshirodk/eap8-app-inventory:latest'
  replicas: 1
  serviceAccountName: eap-service-account
  envFrom:
    - configMapRef:
        name: postgres-config
    - configMapRef:
        name: keystore-config
    - secretRef:
        name: postgres-credentials
    - secretRef:
        name: keystore-credentials
  secrets:
    - keystore